using Godot;
using System;

/// <summary>
/// Pops up when the game is over to let the player know they lost
/// </summary>
public class GameOverMessage : TextureRect
{
	private void gimmetheuhautogeneratedfunctionname()
	{
		Visible = true;
	}
}
